###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  user:
    password: "$argon2id$v=19$m=1048576,t=1,p=8$dm9aZHpPcGpQVmMzdVkyVA$3u3Zcpp2/MB0eBfmpNlKgeOH4RqpJHjG2sjj/dX4JU0"
    email: youremail@domain.com
    groups:
      - admins
      - dev